ALTER TABLE players ADD COLUMN IF NOT EXISTS auth_user_id UUID UNIQUE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS avatar_path TEXT DEFAULT '';
ALTER TABLE players ADD COLUMN IF NOT EXISTS locale TEXT DEFAULT 'en';
ALTER TABLE players ADD COLUMN IF NOT EXISTS preferred_card_skin TEXT DEFAULT 'clasica';
ALTER TABLE players ADD COLUMN IF NOT EXISTS sound_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS espada_obligatoria BOOLEAN DEFAULT TRUE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS sound_volume DOUBLE PRECISION DEFAULT 0.7;
ALTER TABLE players ADD COLUMN IF NOT EXISTS colorblind_mode BOOLEAN DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS table_theme TEXT DEFAULT 'classic';
ALTER TABLE players ADD COLUMN IF NOT EXISTS animation_speed TEXT DEFAULT 'normal';
ALTER TABLE players ADD COLUMN IF NOT EXISTS reduce_motion BOOLEAN DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_players_auth_user_id ON players(auth_user_id);
